---
theme: dark
jwt_secret: a_very_important_secret
default_redirection_url: http://google.com
default_2fa_method: ""

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  disable_healthcheck: false

log:
  level: debug
  format: json

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 1m

  ldap:
    implementation: custom
    url: ldap://openldap
    timeout: 30s
    start_tls: false
    base_dn: dc=kwkaiser,dc=io
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    username_attribute: uid
    mail_attribute: mail
    display_name_attribute: displayName
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    group_name_attribute: cn
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: CN=admin,DC=kwkaiser,DC=io
    password: password

password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true
  zxcvbn:
    enabled: false
    min_score: 3

# privacy_policy:
#   enabled: false
#   require_user_acceptance: false
#   policy_url: ""

access_control:
  default_policy: deny
  rules:
    - domain: scurvy.{{ .Values.domain-name }}
      policy: one_factor
      subject:
        - ["user:kwkaiser"]

storage:
  encryption_key: a_very_important_secret
  local:
    path: /config/db.sqlite3

session:
  domain: localhost
  secret: insecure_session_secret
  name: authelia_session
  same_site: lax
  inactivity: 5m
  expiration: 1h

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

notifier:
  disable_startup_check: true
  filesystem:
    filename: /cnofig/notification.txt
