apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux-db
spec:
  selector:
    matchLabels:
      app: miniflux-db
  replicas: 1
  template:
    metadata:
      labels:
        app: miniflux-db
        app.kubernetes.io/name: miniflux-db
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: miniflux-db
          image: {{ .Values.image_miniflux_db }}
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: miniflux

            - name: POSTGRES_PASSWORD
              value: password

            - name: POSTGRES_DB
              value: miniflux

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: application/miniflux/db
