apiVersion: v1
kind: Service
metadata:
  name: miniflux-db
spec:
  selector:
    app: miniflux-db
    app.kubernetes.io/name: miniflux-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
