apiVersion: apps/v1
kind: Deployment
metadata:
  name: steam
spec:
  selector:
    matchLabels:
      app: steam
  replicas: 1
  template:
    metadata:
      labels:
        app: steam
        app.kubernetes.io/name: steam
    spec:
      hostNetwork: true
      securityContext:
        fsGroup: 1000

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        - name: dshm
          emptyDir:
            medium: Memory

      containers:
        - name: steam
          securityContext:
            privileged: true
          image: lscr.io/linuxserver/steamos:latest
          resources: #Change CPU and Memory below
            requests:
              memory: "4G"
              cpu: "2"
            limits:
              memory: "4G"
              cpu: "2"

          ports:
            - containerPort: 3000
            - containerPort: 3001

          env: #Environmental Vars
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: DRINODE
              value: /dev/dri/renderD128
            - name: STARTUP
              value: KDE #optional
            - name: RESOLUTION
              value: 1920x1080 #optional

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/steam/config

            - name: data
              mountPath: /dev/dri
              subPath: application/steam/dev

            - name: dshm
              mountPath: /dev/shm
