source_directories:
    - /bulk/application/autobrr
    - /bulk/application/gitea/data
    - /bulk/application/gitea/repos
    - /bulk/application/jellyfin
    - /bulk/application/prometheus 
    - /bulk/application/qbittorrent
    - /bulk/application/registry
    - /bulk/application/calibre
    - /bulk/application/grafana
    - /bulk/application/loki
    - /bulk/application/openldap
    - /bulk/application/prowlarr
    - /bulk/application/radarr
    - /bulk/application/sonarr
    - /bulk/shared/books

# postgresql_databases:
#   - name: postgres
#     hostname: giteadb
#     username: postgres
#     password: ${GITEA_DB_PASSWORD}
#     format: tar

#   - name: miniflux
#     hostname: minifluxdb
#     username: postgres
#     password: ${MINIFLUX_DB_PASSWORD}
#     format: tar

repositories:
    - path: /raw-backup
      label: local

after_backup:
    - cd /
    - tar xvf ./tar-dir/backup.tar ./raw-backup
    - du -sh ./tar-dir/backup.tar
