source_directories:
  - /bulk/application/gitea/data
  - /bulk/application/gitea/repos
  - /bulk/application/jellyfin
  - /bulk/application/qbittorrent
  - /bulk/application/registry
  - /bulk/application/calibre
  - /bulk/application/openldap
  - /bulk/application/prowlarr
  - /bulk/application/radarr
  - /bulk/application/sonarr
  - /bulk/application/immich/media
  - /bulk/application/syncthing
  - /bulk/shared/books

retention:
  keep_within: 3H
  keep_minutely: 60
  keep_hourly: 24
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6
  keep_yearly: 1

postgresql_databases:
  - name: postgres
    hostname: giteadb
    username: postgres
    password: ${GITEA_DB_PASSWORD}
    format: tar

  - name: postgres
    hostname: minifluxdb
    username: postgres
    password: ${MINIFLUX_DB_PASSWORD}
    format: tar

  - name: postgres
    hostname: immichdb
    username: postgres
    password: ${IMMICH_DB_PASSWORD}
    format: tar

  - name: postgres
    hostname: mealiedb
    username: postgres
    password: ${MEALIE_DB_PASSWORD}
    format: tar

repositories:
  - path: /raw-backup
    label: local

after_backup:
  - borg check /raw-backup --verify-data && echo 'data integrity check ok, uploading' || exit 1
  - apk update
  - pip install s3cmd
  - tar cvf /tar-dir/{{ .Values.backupName}}.tar /raw-backup/*
  - s3cmd put /tar-dir/{{ .Values.backupName }}.tar s3://borg-backup/{{ .Values.backupName }}.tar --access_key=${LINODE_CLI_OBJ_ACCESS_KEY} --secret_key=${LINODE_CLI_OBJ_SECRET_KEY} --host='borg-backup.us-east-1.linodeobjects.com' --host-bucket='borg-backup'

extra_borg_options:
  init: --verbosity 2
  create: --verbosity 2
  prune: --verbosity 2
  compact: --verbosity 2
  check: --verbosity 2