source_directories:
  - /bulk/application/autobrr
  - /bulk/application/gitea/data
  - /bulk/application/gitea/repos
  - /bulk/application/jellyfin
  - /bulk/application/prometheus 
  - /bulk/application/qbittorrent
  - /bulk/application/registry
  - /bulk/application/calibre
  - /bulk/application/grafana
  - /bulk/application/loki
  - /bulk/application/openldap
  - /bulk/application/prowlarr
  - /bulk/application/radarr
  - /bulk/application/sonarr
  - /bulk/shared/books

postgresql_databases:
  - name: postgres
    hostname: giteadb
    username: postgres
    password: ${GITEA_DB_PASSWORD}
    format: tar

  # - name: postgres
  #   hostname: minifluxdb
  #   username: postgres
  #   password: ${MINIFLUX_DB_PASSWORD}
  #   format: tar

repositories:
  - path: /raw-backup
    label: local

after_backup:
  - apk update
  - pip install linode-cli
  - tar cvf /tar-dir/{{ .Values.backupName}}.tar /raw-backup/*
  - cd /tar-dir && linode-cli obj put {{ .Values.backupName }}.tar borg-backup --cluster us-east-1
  
