apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
spec:
  selector:
    matchLabels:
      app: readarr
  replicas: 1
  template:
    metadata:
      labels:
        app: readarr
        app.kubernetes.io/name: readarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: readarr
          image: {{ .Values.image_readarr }}
          ports:
            - containerPort: 7878

          env:
            - name: PUID
              value: "0"

            - name: PGID
              value: "0"

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/readarr

            - name: data
              mountPath: /shared/torrents
              subPath: shared/torrents

            - name: data
              mountPath: /shared/books
              subPath: shared/books