apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
spec:
  selector:
    matchLabels:
      app: authelia
  replicas: 1
  template:
    metadata:
      labels:
        app: authelia
        app.kubernetes.io/name: authelia
    spec:
      volumes:
        - name: authelia-configs
          configMap:
            name: authelia-configs
            items:
              - key: configuration.yaml
                path: configuration.yaml

      containers:
        - name: authelia
          image: {{ .Values.image_authelia }}
          ports:
            - containerPort: 80

          volumeMounts:
            - name: authelia-configs
              mountPath: /config/configuration.yml # expects path at .yml!
              subPath: configuration.yaml
              readOnly: false

      initContainers:
        {{ include "waitFor" (dict "Name" "openldap" "Port" 389) }}
      
