apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
spec:
  selector:
    matchLabels:
      app: authelia
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/authelia/cm.yaml") . | sha256sum }}
      labels:
        app: authelia
        app.kubernetes.io/name: authelia
    spec:
      volumes:
        - name: authelia-configs
          configMap:
            name: authelia-configs
            items:
              - key: configuration.yaml
                path: configuration.yaml

      containers:
        - name: authelia
          image: {{ .Values.image_authelia }}
          ports:
            - containerPort: 80

          env:
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap.binddn.password
                  key: value

            - name: AUTHELIA_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: authelia.session.secret
                  key: value

            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: authelia.encryption.key
                  key: value

          volumeMounts:
            - name: authelia-configs
              mountPath: /config/configuration.yml # expects path at .yml!
              subPath: configuration.yaml
              readOnly: false

      initContainers:
        {{ include "waitFor" (dict "Name" "openldap" "Port" 389) }}
      
