apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
spec:
  selector:
    matchLabels:
      app: authelia
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/authelia/cm.yaml") . | sha256sum }}
      labels:
        app: authelia
        app.kubernetes.io/name: authelia
    spec:
      volumes:
        - name: authelia-configs
          configMap:
            name: authelia-configs
            items:
              - key: configuration.yaml
                path: configuration.yaml

        {{- range $name := list "openldap-binddn-pw" }}
        - name: {{$name}}
          secret:
            secretName: {{ regexReplaceAll "-" $name "." }}
            items:
              - key: value
                path: value
        {{- end }}

      containers:
        - name: authelia
          image: {{ .Values.image_authelia }}
          ports:
            - containerPort: 80

          env:
            - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
              value: /openldap-binddn-pw.txt

          volumeMounts:
            - name: openldap-binddn-pw
              mountPath: /openldap-binddn-pw.txt 
              subPath: value
              readOnly: true

            - name: authelia-configs
              mountPath: /config/configuration.yml # expects path at .yml!
              subPath: configuration.yaml
              readOnly: false

      initContainers:
        {{ include "waitFor" (dict "Name" "openldap" "Port" 389) }}
      
