apiVersion: v1
kind: Service
metadata:
  name: dawarichdb
spec:
  selector:
    app: dawarichdb
    app.kubernetes.io/name: dawarichdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
