apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  selector:
    matchLabels:
      app: qbittorrent
  replicas: 1
  template:
    metadata:
      labels:
        app: qbittorrent
        app.kubernetes.io/name: qbittorrent
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"
          - name: net.ipv6.conf.all.disable_ipv6
            value: "0"

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        {{- range $name := list "wireguard-key" }}
        - name: {{$name}}
          secret:
            secretName: {{ regexReplaceAll "-" $name "." }}
            items:
              - key: value
                path: value
        {{- end }}

      containers:
        - name: wireguard
          image: {{ .Values.image_wireguard }}
          ports:
            - containerPort: 51820

          volumeMounts:
            - name: wireguard-key
              mountPath: /config/wg0.conf
              subPath: value

          # Hooks to guarantee we connected to target IP & stayed connected.
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30 && until curl --connect-timeout 10 ifconfig.me | grep -i "{{ .Values.qbittorrentIp }}"; do echo "Waiting for ifconfig response"; sleep 10; done;
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_BIND
                - NET_RAW
                - SYS_MODULE

        - name: qbittorrent
          image: {{ .Values.image_qbittorrent }}
          ports:
            - containerPort: 8080
            - containerPort: 6881

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/qbittorrent

            - name: data
              mountPath: /shared/torrents
              subPath: shared/torrents  

        