apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec: 
  selector:
    matchLabels:
      app: qbittorrent
  replicas: 1 
  template:
    metadata:
      labels: 
        app: qbittorrent
        app.kubernetes.io/name: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: linuxserver/qbittorrent
          ports:
            - containerPort: 8080
            - containerPort: 6881