apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  selector:
    app: qbittorrent
    app.kubernetes.io/name: qbittorrent
  ports:
    - protocol: TCP
      name: qbittorrent
      port: 80
      targetPort: 8080
