## Global values
global:
  domainName: kwkaiser-test
  tld: io

## Storage related values
storage:
  enabled: true
  nfsArray: "10.0.2.15"
  volBulkSize: 1Gi
  volCacheSize: 1Gi

core:
  enabled: true

dashy:
  enabled: false

authentik:
  enabled: false

gitea:
  enabled: false

immich:
  enabled: false

mealie:
  enabled: false

miniflux:
  enabled: false

media:
  enabled: false

observability:
  enabled: false
  promHosts: ["10.0.2.15:9100"]

vpn:
  enabled: false
  qbittorrentIp: "143.244.47.73"

borgmatic:
  enabled: false

calibre-web:
  enabled: false

jellyfin:
  enabled: false

minecraft:
  enabled: false

syncthing:
  enabled: false
