## Global values
_global: &global_values
  domainName: kwkaiser-test
  tld: io
<<: *global_values
global:
  <<: *global_values

## Storage related values
_storage: &storage_values
  nfsArray: "10.0.2.15"
  volBulkSize: 1Gi
  volCacheSize: 1Gi
<<: *storage_values
storage:
  <<: *storage_values
  enabled: true

piracyIp: "143.244.47.73"
promHosts: ["10.0.2.15:9100"]
backupName: dev-backup

core:
  enabled: true

gitea:
  enabled: false

immich:
  enabled: false

mealie:
  enabled: false

miniflux:
  enabled: false

media:
  enabled: false

observability:
  enabled: false
  promHosts: ["10.0.2.15:9100"]

vpn:
  enabled: false
  qbittorrentIp: "143.244.47.73"
