## Global values
global:
  domainName: kwkaiser
  tld: io

## Storage related values
storage:
  enabled: true
  nfsArray: "192.168.2.103"
  volBulkSize: 14.4T
  volCacheSize: 220G

core:
  enabled: true

gitea:
  enabled: true

immich:
  enabled: true

mealie:
  enabled: true

miniflux:
  enabled: true

media:
  enabled: true

observability:
  enabled: true
  promHosts: ["192.168.2.103:9100"]

vpn:
  enabled: true
  qbittorrentIp: "143.244.47.73"

borgmatic:
  enabled: true

calibre-web:
  enabled: true

jellyfin:
  enabled: true

minecraft:
  enabled: false

syncthing:
  enabled: true
