## Global values
_global: &global_values
  domainName: kwkaiser
  tld: io
<<: *global_values
global:
  <<: *global_values

## Storage related values
_storage: &storage_values
  nfsArray: "192.168.2.103"
  volBulkSize: 14.4T
  volCacheSize: 220G
<<: *storage_values
storage:
  <<: *storage_values
  enabled: true

piracyIp: "143.244.47.73"
promHosts: ["192.168.2.103:9100"]
backupName: prod-backup

core:
  enabled: true

gitea:
  enabled: true

immich:
  enabled: true

mealie:
  enabled: true

miniflux:
  enabled: true
