## Global values
global:
  domainName: kwkaiser
  tld: io

## Storage related values
storage:
  enabled: true
  nfsArray: "127.0.0.1"
  volBulkSize: 60Gi
  volCacheSize: 15Gi

core:
  enabled: true
  authelia:
    enabled: false

dashy:
  enabled: false

gitea:
  enabled: true

website:
  enabled: true

immich:
  enabled: true

mealie:
  enabled: true

miniflux:
  enabled: true

media:
  enabled: false

observability:
  enabled: false
  promHosts: ["192.168.2.103:9100"]

vpn:
  enabled: false

borgmatic:
  enabled: true
  opnsenseHost: "192.168.1.1"

calibre-web:
  enabled: true

jellyfin:
  enabled: false

minecraft:
  enabled: false

syncthing:
  enabled: true
