# Certain pods need to have their DNS re-written to allow for the same host-mapping
# behavior we use in the vm-host (generally under /etc/hosts), but using coreDNS to have it
# apply at the pod level. This is applied separately from
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        rewrite name exact authentik.kwkaiser-test.io authentik-server.default.svc.cluster.local
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
        forward . /etc/resolv.conf
    }
