apiVersion: v1
kind: Service
metadata:
  name: calibre-web
spec:
  selector:
    app: calibre-web
    app.kubernetes.io/name: calibre-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
