server {
  listen 443 ssl;
  include https.conf;

  server_name housing.*;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Real-IP $remote_addr;

    set $housing_upstream http://housing.default.svc.cluster.local;
    proxy_pass $housing_upstream;

    include authentik-location.conf;
  }

  include authentik-proxy.conf;
}
