apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  selector:
    matchLabels:
      app: couchdb
  replicas: 1
  template:
    metadata:
      labels:
        app: couchdb
        app.kubernetes.io/name: couchdb
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: couchdb
          image: {{ .Values.image_couchdb }}
          ports:
            - containerPort: 5984

          env:
            - name: COUCHDB_USER
              value: admin
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb.admin.password
                  key: value

          volumeMounts:
            - name: data
              mountPath: /opt/couchdb/data
              subPath: application/couchdb
