apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
        app.kubernetes.io/name: sonarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: sonarr
          image: {{ .Values.image_sonarr }}
          ports:
            - containerPort: 8989

          env:
            - name: PUID
              value: "0"

            - name: PGID
              value: "0"

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/sonarr

            - name: data
              mountPath: /shared/torrents
              subPath: shared/torrents

            - name: data
              mountPath: /shared/tv
              subPath: shared/tv

