apiVersion: v2
name: homelab
description: Chart for deploying homelab / my server infra
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: reloader
    version: "2.2.5"
    repository: https://stakater.github.io/stakater-charts

  # Storage (NFS volumes)
  - name: storage
    version: "0.1.0"
    repository: file://./helmcharts/storage
    condition: storage.enabled

  # Core infrastructure (Nginx, Authelia, OpenLDAP)
  - name: core
    version: "0.1.0"
    repository: file://./helmcharts/core
    condition: core.enabled

  - name: dashy
    version: "0.1.0"
    repository: file://./helmcharts/dashy
    condition: dashy.enabled

  # Gitea (Git service, database, renovate, runner)
  - name: gitea
    version: "0.1.0"
    repository: file://./helmcharts/gitea
    condition: gitea.enabled

  # Immich (Photo management, database, redis, ML)
  - name: immich
    version: "0.1.0"
    repository: file://./helmcharts/immich
    condition: immich.enabled

  # Mealie (Recipe management, database)
  - name: mealie
    version: "0.1.0"
    repository: file://./helmcharts/mealie
    condition: mealie.enabled

  # Miniflux (RSS reader, database)
  - name: miniflux
    version: "0.1.0"
    repository: file://./helmcharts/miniflux
    condition: miniflux.enabled

  # Media (Radarr, Sonarr, Prowlarr)
  - name: media
    version: "0.1.0"
    repository: file://./helmcharts/media
    condition: media.enabled

  # Observability (Prometheus, Grafana, Loki, Promtail)
  - name: observability
    version: "0.1.0"
    repository: file://./helmcharts/observability
    condition: observability.enabled

  # VPN (WireGuard, qBittorrent, TheLounge, Kasm)
  - name: vpn
    version: "0.1.0"
    repository: file://./helmcharts/vpn
    condition: vpn.enabled

  # Borgmatic (Backup solution)
  - name: borgmatic
    version: "0.1.0"
    repository: file://./helmcharts/borgmatic
    condition: borgmatic.enabled

  # Calibre Web (E-book server)
  - name: calibre-web
    version: "0.1.0"
    repository: file://./helmcharts/calibre-web
    condition: calibre-web.enabled

  # Jellyfin (Media server)
  - name: jellyfin
    version: "0.1.0"
    repository: file://./helmcharts/jellyfin
    condition: jellyfin.enabled

  # Minecraft (Game server)
  - name: minecraft
    version: "0.1.0"
    repository: file://./helmcharts/minecraft
    condition: minecraft.enabled

  # Syncthing (File synchronization)
  - name: syncthing
    version: "0.1.0"
    repository: file://./helmcharts/syncthing
    condition: syncthing.enabled
