apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-runner
spec:
  selector:
    matchLabels:
      app: gitea-runner
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea-runner
        app.kubernetes.io/name: gitea-runner
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: gitea-runner
          image: {{ .Values.image_gitea_runner }}

          securityContext:
            privileged: true

          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2376

            - name: DOCKER_CERT_PATH
              value: /certs/client

            - name: DOCKER_TLS_VERIFY
              value: "1"

            - name: GITEA_INSTANCE_URL
              value: "http://gitea"

            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea.runner.token
                  key: value

          volumeMounts:
            - name: data
              mountPath: /data
              subPath: application/gitea/runner

      initContainers: 
        {{ include "waitFor" (dict "Name" "gitea" "Port" 80) }}
