apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-runner
spec:
  selector:
    matchLabels:
      app: gitea-runner
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea-runner
        app.kubernetes.io/name: gitea-runner
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        - name: docker-certs
          emptyDir: {}

      securityContext:
        fsGroup: 1000

      containers:
        - name: gitea-runner
          image: {{ .Values.image_gitea_runner }}

          securityContext:
            privileged: true

          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2376

            - name: DOCKER_CERT_PATH
              value: /certs/client

            - name: DOCKER_TLS_VERIFY
              value: "1"

            - name: GITEA_INSTANCE_URL
              value: "http://gitea"

            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea.runner.token
                  key: value

          volumeMounts:
            - name: docker-certs
              mountPath: /certs
            - name: data
              mountPath: /data
              subPath: application/gitea/runner

        - name: daemon
          image: docker:23.0.6-dind
          env:
          - name: DOCKER_TLS_CERTDIR
            value: /certs

          securityContext:
            privileged: true

          volumeMounts:
          - name: docker-certs
            mountPath: /certs

      initContainers: 
        {{ include "waitFor" (dict "Name" "gitea" "Port" 80) }}
