scrape_configs:
  - job_name: pods
    static_configs:
      - targets: 
          - localhost
        labels: 
          job: pod
          __path__: /var/log/containers/*.log
    pipeline_stages:
      - cri: {}
      - match:
          selector: '{job="pod"}'
          stages:
            - regex:
                source: filename
                expression: (\/var\/log\/containers\/)(?P<containerName>.+)(-.+-.+_default_.+)
            - labels:
                containerName:
            - labeldrop:
                - filename

clients: 
  - url: 'http://loki/loki/api/v1/push'