scrape_configs:
  - job_name: pods
    static_configs:
      - targets: 
          - localhost
        labels: 
          job: pods
          __path__: /var/log/containers/*.log

clients: 
  - url: 'http://loki/loki/api/v1/push'