apiVersion: v1
kind: PersistentVolume
metadata:
  name: bulk-nfs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: bulk-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /bulk-pool/nfs
    server: {{ .Values.nfsArray }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-nfs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cache-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /cache-pool/nfs
    server: {{ .Values.nfsArray }}
