apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bulk-nfs
spec:
  storageClassName: bulk-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-nfs
spec:
  storageClassName: cache-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi