apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "immich.db.password"
  name: immich
spec:
  selector:
    matchLabels:
      app: immich
  replicas: 1
  template:
    metadata:
      labels:
        app: immich
        app.kubernetes.io/name: immich
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        - name: cache-data
          persistentVolumeClaim:
            claimName: cache-nfs

      containers:
        - name: redis
          image: {{ .Values.image_immich_redis }}
          ports:
            - containerPort: 6379 

          volumeMounts:
            - name: data
              mountPath: /data
              subPath: application/immich/redis

        - name: immich-ml
          image: {{ .Values.image_immich_ml }}
          ports:
            - containerPort: 3003
          volumeMounts:
            - name: data
              mountPath: /cache
              subPath: application/immich/models

        - name: immich-microservices
          image: {{ .Values.image_immich_server }}
          command: ['/bin/bash']
          args: ['start.sh', 'microservices']
          env:
            - name: DB_USERNAME
              value: postgres

            - name: DB_DATABASE_NAME
              value: postgres

            - name: DB_HOSTNAME
              value: immichdb

            - name: REDIS_HOSTNAME
              value: localhost

            - name: UPLOAD_LOCATION
              value: /usr/src/app/upload

            - name: IMMICH_MEDIA_LOCATION
              value: /usr/src/app/media

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich.db.password
                  key: value

          volumeMounts:
            - name: data
              mountPath: /usr/src/app/upload
              subPath: application/immich/upload
            - name: data
              mountPath: /usr/src/app/media
              subPath: application/immich/media

        - name: immich-server
          image: {{ .Values.image_immich_server }}
          command: ['/bin/bash']
          args: ['start.sh', 'immich']
          ports:
            - containerPort: 3001
          env:
            - name: DB_USERNAME
              value: postgres

            - name: DB_DATABASE_NAME
              value: postgres

            - name: DB_HOSTNAME
              value: immichdb

            - name: REDIS_HOSTNAME
              value: localhost

            - name: UPLOAD_LOCATION
              value: /usr/src/app/upload

            - name: IMMICH_MEDIA_LOCATION
              value: /usr/src/app/media

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich.db.password
                  key: value

          volumeMounts:
            - name: data
              mountPath: /usr/src/app/upload
              subPath: application/immich/upload
            - name: data
              mountPath: /usr/src/app/media
              subPath: application/immich/media

