apiVersion: v1
kind: Service
metadata:
  name: immich
spec:
  selector:
    app: immich
    app.kubernetes.io/name: immich
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
