apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec: 
  selector:
    matchLabels:
      app: openldap
  replicas: 1
  template:
    metadata:
      labels: 
        app: openldap
        app.kubernetes.io/name: openldap
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: openldap
          image: osixia/openldap@sha256:11a30708d9224291c39b2eed1d2620eb9687f4b8411e3b9dac6362ff634794c2
          ports:
            - containerPort: 636
            - containerPort: 389

          args: ["--loglevel", "debug", "--copy-service"]

          env:
            - name: LDAP_ORGANISATION
              value: {{ .Values.domainName }}.{{ .Values.tld }}

            - name: LDAP_DOMAIN
              value: {{ .Values.domainName }}.{{ .Values.tld }}

            - name: LDAP_ADMIN_PASSWORD
              value: password
            
            - name: LDAP_REQUIRE_STARTTLS
              value: "false"

            - name: HOSTNAME
              value: openldap

            - name: LDAP_TLS
              value: "false"

            - name: LDAP_RFC2307BIS_SCHEMA
              value: "true"

          volumeMounts:
            - name: data
              mountPath: /var/lib/ldap
              subPath: application/openldap/data

            - name: data 
              mountPath: /etc/ldap/slapd.d
              subPath: application/openldap/slapd

            