apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea
        app.kubernetes.io/name: gitea
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: gitea
          image: {{ .Values.image_gitea }}
          ports:
            - containerPort: 3000
            - containerPort: 2222

          env:
            - name: GITEA__database__DB_TYPE
              value: postgres

            - name: GITEA__database__HOST
              value: giteadb:5432

            - name: GITEA__database__NAME
              value: postgres

            - name: GITEA__database__USER
              value: postgres

            - name: GITEA__database__PASSWD
              value: password

            - name: GITEA__actions__ENABLED
              value: "true"

            - name: GITEA__metrics__ENABLED
              value: "true"

            - name: GITEA__server__ROOT_URL
              value: "http://gitea"

          volumeMounts:
            - name: data
              mountPath: /data/gitea
              subPath: application/gitea/data

            - name: data
              mountPath: /data/git/repositories
              subPath: application/gitea/repos

            - name: data
              mountPath: /data/git/lfs
              subPath: application/gitea/lfs

      {{ include "waitFor" (dict "Name" "giteadb" "Port" 5432) }}
