apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "gitea.db.password"
  name: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea
        app.kubernetes.io/name: gitea
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: gitea
          image: {{ .Values.image_gitea }}
          ports:
            - containerPort: 3000
            - containerPort: 2222

          env:
            - name: GITEA__database__DB_TYPE
              value: postgres

            - name: GITEA__database__HOST
              value: giteadb:5432

            - name: GITEA__database__NAME
              value: postgres

            - name: GITEA__database__USER
              value: postgres

            - name: GITEA_database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea.db.password
                  key: value

            - name: GITEA__actions__ENABLED
              value: "true"

            - name: GITEA__metrics__ENABLED
              value: "true"

            - name: GITEA__server__ROOT_URL
              value: "http://gitea"

            - name: GITEA__service__SHOW_REGISTRATION_BUTTON
              value: "false"

            - name: GITEA__openid__ENABLE_OPENID_SIGNUP
              value: "false"

            - name: GITEA__openid__ENABLE_OPENID_SIGNIN
              value: "false"

            - name: GIT_SSL_NO_VERIFY
              value: "true"

          volumeMounts:
            - name: data
              mountPath: /data/gitea
              subPath: application/gitea/data

            - name: data
              mountPath: /data/git/repositories
              subPath: application/gitea/repos

            - name: data
              mountPath: /data/git/lfs
              subPath: application/gitea/lfs