apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "gitea.db.password"
  name: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea
        app.kubernetes.io/name: gitea
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        - name: gitea-configs
          configMap:
            name: gitea-configs
            items:
              - key: app.ini
                path: app.ini

      containers:
        - name: gitea
          image: {{ .Values.image_gitea }}
          ports:
            - containerPort: 3000
            - containerPort: 2222

          env:
            - name: GITEA_database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea.db.password
                  key: value

          volumeMounts:
            - name: data
              mountPath: /data/gitea
              subPath: application/gitea/data

            - name: data
              mountPath: /data/git/repositories
              subPath: application/gitea/repos

            - name: data
              mountPath: /data/git/lfs
              subPath: application/gitea/lfs

            - name: gitea-configs
              mountPath: /data/gitea/conf/app.ini
              subPath: app.ini
              readOnly: false