apiVersion: v1
kind: Service
metadata:
  name: authentik-worker
spec:
  selector:
    app: authentik-worker
    app.kubernetes.io/name: authentik-worker
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000

    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
