apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 1
  template:
    metadata:
      labels:
        app: website
        app.kubernetes.io/name: website
    spec:
      containers:
        - name: website
          image: {{ .Values.image_website }}
          ports:
            - containerPort: 80
