apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
spec:
  selector:
    matchLabels:
      app: calibre
  replicas: 1
  template:
    metadata:
      labels:
        app: calibre
        app.kubernetes.io/name: calibre
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: calibre
          image: {{ .Values.image_calibre }}
          ports:
            - containerPort: 8083

          env:
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-calibre

            - name: PUID
              value: "0"

            - name: PGID
              value: "0"

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/calibre

            - name: data
              mountPath: /books
              subPath: shared/books
