apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
spec:
  selector:
    matchLabels:
      app: calibre
  replicas: 1
  template:
    metadata:
      labels:
        app: calibre
        app.kubernetes.io/name: calibre
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: calibre
          image: {{ .Values.image_calibre }}
          ports:
            - containerPort: 8080
            - containerPort: 8081

          env:
            - name: PUID
              value: "0"

            - name: PGID
              value: "0"

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/calibre

            - name: data
              mountPath: /shared/books
              subPath: shared/books

            - name: data
              mountPath: /shared/upload
              subPath: shared/upload

            - name: data
              mountPath: /shared/torrents/books
              subPath: shared/torrents/books
