apiVersion: v1
kind: Service
metadata:
  name: calibre
spec:
  selector:
    app: calibre
    app.kubernetes.io/name: calibre
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

    - name: content server
      protocol: TCP
      port: 8081
      targetPort: 8081