apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-registry-prune
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitea-registry-prune
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["list"]

  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitea-registry-prune
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitea-registry-prune
subjects:
  - kind: ServiceAccount
    name: gitea-registry-prune
    namespace: {{ .Release.Namespace }}
