apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-renovate
spec:
  selector:
    matchLabels:
      app: gitea-renovate
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea-renovate
        app.kubernetes.io/name: gitea-renovate
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        - name: renovate-configs
          configMap:
            name: renovate-configs
            items:
              - key: config.json
                path: config.json

      containers:
        - name: gitea-renovate
          image: renovate/renovate:37.33-full

          env:
            - name: LOG_LEVEL
              value: debug

            - name: RENOVATE_CONFIG_FILE
              value: /usr/src/app/config.json

            - name: RENOVATE_AUTODISCOVER
              value: "true"

          volumeMounts:
            - name: renovate-configs
              mountPath: /usr/src/app/config.json
              subPath: config.json
              readOnly: false

      initContainers: 
        {{ include "waitFor" (dict "Name" "gitea" "Port" 80)}}
