apiVersion: v2
name: webserver
description: Webserver configuration for homelab
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: common
    version: ">0.0.0-0"
    repository: "file://../common"
