name: Deploy

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    name: Check code quality
    uses: ./.gitea/workflows/code-quality.yaml

  release:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo 'foo'