name: Pull request

on:
  pull_request_target:
    branches:
      - "**"

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo -y

      - name: Install helm
        run: |
          apt-get install curl gpg apt-transport-https --yes
          curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          apt-get update
          apt-get install helm

      - name: Install kubeconform
        run: |
          wget https://github.com/yannh/kubeconform/releases/download/v0.6.4/kubeconform-linux-amd64.tar.gz
          tar xf kubeconform-linux-amd64.tar.gz
          cp kubeconform /usr/local/bin
          rm -rf ./kubeconform*

      - name: Install taskfile
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          cp ./bin/task /usr/local/bin
          rm -rf ./bin

      - name: Lint helm chart
        run: task lint --yes
