apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyin
spec: 
  selector:
    matchLabels:
      app: jellyin
  replicas: 1
  template:
    metadata:
      labels: 
        app: jellyin
        app.kubernetes.io/name: jellyin
    spec:
      containers:
        - name: jellyin
          image: linuxserver/jellyin
          ports:
            - containerPort: 8888
            - containerPort: 9000