apiVersion: batch/v1
kind: CronJob
metadata:
  name: borgmatic
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: bulk-data
              persistentVolumeClaim:
                claimName: bulk-nfs

            - name: cache-data
              persistentVolumeClaim:
                claimName: cache-nfs

            - name: borgmatic-configs
              configMap:
                name: borgmatic-configs
                items:
                  - key: config.yaml
                    path: config.yaml

          containers:
            - name: gitea-renovate
              image: {{ .Values.image_borgmatic }}

              env:
                - name: MINIFLUX_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: miniflux.db.password
                      key: value

                - name: GITEA_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: gitea.db.password
                      key: value

                - name: RUN_ON_STARTUP
                  value: 'true'
                
                - name: CONFIG_PATHS
                  value: /config.yaml

                - name: BORG_PASSPHRASE
                  value: foo

              volumeMounts:
                - name: bulk-data
                  mountPath: /bulk

                - name: bulk-data
                  mountPath: /etc/borgmatic.d
                  subPath: /application/borgmatic

                - name: cache-data
                  mountPath: /cache
                  subPath: /application/borgmatic

                - name: borgmatic-configs
                  mountPath: /config.yaml
                  subPath: config.yaml
                  readOnly: false