apiVersion: batch/v1
kind: CronJob
metadata:
  name: borgmatic
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: bulk-data
              persistentVolumeClaim:
                claimName: bulk-nfs

            - name: cache-data
              persistentVolumeClaim:
                claimName: cache-nfs

            - name: borgmatic-configs
              configMap:
                name: borgmatic-configs
                items:
                  - key: config.yaml
                    path: config.yaml

          initContainers:
            - name: borgmatic-init
              image: {{ .Values.image_borgmatic }}

              command: ["/usr/local/bin/borgmatic"]
              args: ["rcreate", "-e", "repokey"]

              env:
                - name: MINIFLUX_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: miniflux.db.password
                      key: value

                - name: LINODE_CLI_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: linode.cli.token
                      key: value

                - name: LINODE_CLI_OBJ_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: linode.cli.obj.access.key
                      key: value

                - name: LINODE_CLI_OBJ_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: linode.cli.obj.secret.key
                      key: value

                - name: GITEA_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: gitea.db.password
                      key: value

                - name: BACKUP_CRON
                  value: '*/1 * * * *' 

                - name: BORG_PASSPHRASE
                  value: foo

              volumeMounts:
                - name: bulk-data
                  mountPath: /bulk

                - name: cache-data
                  mountPath: /raw-backup
                  subPath: application/borgmatic/backup

                - name: borgmatic-configs
                  mountPath: /etc/borgmatic/config.yaml
                  subPath: config.yaml
                  readOnly: false

          containers:
            - name: borgmatic-create
              image: {{ .Values.image_borgmatic }}

              command: ["/usr/local/bin/borgmatic"]
              args: ["create"]

              env:
                - name: MINIFLUX_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: miniflux.db.password
                      key: value

                - name: GITEA_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: gitea.db.password
                      key: value

                - name: BACKUP_CRON
                  value: '*/1 * * * *' 

                - name: BORG_PASSPHRASE
                  value: foo

              volumeMounts:
                - name: bulk-data
                  mountPath: /bulk

                - name: cache-data
                  mountPath: /raw-backup
                  subPath: application/borgmatic/backup

                - name: cache-data
                  mountPath: /tar-dir
                  subPath: application/borgmatic/tardir

                - name: borgmatic-configs
                  mountPath: /etc/borgmatic/config.yaml
                  subPath: config.yaml
                  readOnly: false