apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec: 
  selector:
    matchLabels:
      app: keycloak
  replicas: 1
  template:
    metadata:
      labels: 
        app: keycloak
        app.kubernetes.io/name: keycloak
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak
          args: ["start-dev"] 
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
