apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
    app.kubernetes.io/name: registry
  ports:
    - name: registry
      protocol: TCP
      port: 443
      targetPort: 5000
