apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec: 
  selector:
    matchLabels:
      app: openldap
  replicas: 1
  template:
    metadata:
      labels: 
        app: openldap
        app.kubernetes.io/name: openldap
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: openldap
          image: osixia/openldap
          ports:
            - containerPort: 636
            - containerPort: 389

          env:
            - name: LDAP_ORGANISATION
              value: kwkaiser.io
            - name: LDAP_DOMAIN
              value: kwkaiser.io
            - name: LDAP_ADMIN_PASSWORD
              value: password
            - name: LDAP_REQUIRE_STARTTLS
              value: "false"
            - name: LDAP_TLS
              value: "false"

          volumeMounts:
            - name: data
              mountPath: /var/lib/ldap
              subPath: application/openldap/data

            - name: data 
              mountPath: /etc/ldap/slapd.d
              subPath: application/openldap/slapd
 
