apiVersion: apps/v1
kind: Deployment
metadata:
  name: piracy
spec:
  selector:
    matchLabels:
      app: piracy
  replicas: 1
  template:
    metadata:
      labels:
        app: piracy
        app.kubernetes.io/name: piracy
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"
          - name: net.ipv6.conf.all.disable_ipv6
            value: "0"

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        {{- range $name := list "wireguard-key" }}
        - name: {{$name}}
          secret:
            secretName: {{ regexReplaceAll "-" $name "." }}
            items:
              - key: value
                path: value
        {{- end }}

      containers:
        - name: wireguard
          image: {{ .Values.image_wireguard }}
          ports:
            - containerPort: 51820

          volumeMounts:
            - name: wireguard-key
              mountPath: /config/wg0.conf
              subPath: value

          # Hooks to guarantee we connected to target IP & stayed connected.
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30 && until curl --connect-timeout 10 ifconfig.me | grep -i "{{ .Values.piracyIp }}"; do echo "Waiting for ifconfig response"; sleep 10; done;
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - exit "$(curl ifconfig.me --connect-timeout 30 | grep -i '{{ .Values.piracyIp }}')"
            initialDelaySeconds: 120
            periodSeconds: 120
            timeoutSeconds: 30

          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_BIND
                - NET_RAW
                - SYS_MODULE

        - name: qbittorrent
          image: {{ .Values.image_qbittorrent }}
          ports:
            - containerPort: 8080
            - containerPort: 6881

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/qbittorrent

            - name: data
              mountPath: /shared/torrents
              subPath: shared/torrents

        - name: radarr
          image: {{ .Values.image_radarr }}
          ports:
            - containerPort: 7878

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/radarr

            - name: data
              mountPath: /shared/torrents
              subPath: shared/torrents

            - name: data
              mountPath: /shared/movies
              subPath: shared/movies    

        - name: sonarr
          image: {{ .Values.image_sonarr }}
          ports:
            - containerPort: 8989

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/sonarr

            - name: data
              mountPath: /shared/torrents
              subPath: shared/torrents

            - name: data
              mountPath: /shared/tv
              subPath: shared/tv

        - name: prowlarr
          image: {{ .Values.image_prowlarr }}
          ports:
            - containerPort: 9696

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/prowlarr

        - name: autobrr
          image: ghcr.io/autobrr/autobrr:latest
          ports:
            - containerPort: 7474

          env:
            - name: AUTOBRR__HOST
              value: "0.0.0.0"

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/autobrr