apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/observability/grafana/cm.yaml") . | sha256sum }}
      labels:
        app: grafana
        app.kubernetes.io/name: grafana
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        - name: grafana-configs
          configMap:
            name: grafana-configs
            items:
              - key: config.ini
                path: config.ini

      containers:
        - name: grafana
          image: {{ .Values.image_grafana }}
          ports:
            - containerPort: 3000
          args:
            - "--config=/config.ini"

          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
              subPath: application/grafana

            - name: grafana-configs
              mountPath: config.ini 
              subPath: config.ini
              readOnly: false
