apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
spec:
  selector:
    matchLabels:
      app: miniflux
  replicas: 1
  template:
    metadata:
      labels:
        app: miniflux
        app.kubernetes.io/name: miniflux
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: miniflux
          image: {{ .Values.image_miniflux }}
          ports:
            - containerPort: 8080

          env:
            - name: METRICS_COLLECTOR
              value: "1"

            - name: RUN_MIGRATIONS
              value: "1"

            - name: CREATE_ADMIN
              value: "1"

            - name: ADMIN_USERNAME
              value: kwkaiser

            - name: ADMIN_PASSWORD
              value: password

            - name: DATABASE_URL
              value: postgres://miniflux:password@miniflux-db/miniflux?sslmode=disable
      initContainers:
        {{ include "waitFor" (dict "Name" "miniflux-db" "Port" 5432) }}
