apiVersion: v1
kind: Service
metadata:
  name: sparkyfitnessdb
spec:
  selector:
    app: sparkyfitnessdb
    app.kubernetes.io/name: sparkyfitnessdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
