apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec: 
  type: NodePort
  selector:
    app: minecraft
  ports:
    - name: mc 
      protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 25565