apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "mealie.db.password"
  name: mealie
spec:
  selector:
    matchLabels:
      app: mealie
  replicas: 1
  template:
    metadata:
      labels:
        app: mealie
        app.kubernetes.io/name: mealie
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: mealie
          image: {{ .Values.image_mealie }}
          ports:
            - containerPort: 9000

          env:
            - name: ALLOW_SIGNUP
              value: "false"

            - name: API_DOCS
              value: "false"

            - name: BASE_URL
              value: https://food.{{ .Values.global.domainName }}.{{ .Values.global.tld }}

            - name: FORWARDED_ALLOW_IPS
              value: "*"

            - name: DB_ENGINE
              value: postgres

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_SERVER
              value: mealiedb

            - name: POSTGRES_DB
              value: postgres

            - name: OIDC_AUTH_ENABLED
              value: "true"

            - name: OIDC_PROVIDER_NAME
              value: "authentik"

            - name: OIDC_CONFIGURATION_URL
              value: "https://authentik.{{ .Values.global.domainName }}.{{ .Values.global.tld }}/application/o/mealie/.well-known/openid-configuration"

            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mealie.oidc.clientid
                  key: value

            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mealie.oidc.clientsecret
                  key: value

            - name: OIDC_SIGNUP_ENABLED
              value: "true"

            - name: OIDC_ADMIN_GROUP
              value: "mealie-admin"

            - name: OIDC_REMEMBER_ME
              value: "true"

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie.db.password
                  key: value

          volumeMounts:
            - name: data
              mountPath: /app/data
              subPath: application/mealie/app
