apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-user-manager
spec: 
  selector:
    matchLabels:
      app: ldap-user-manager
  replicas: 1 
  template:
    metadata:
      labels: 
        app: ldap-user-manager
        app.kubernetes.io/name: ldap-user-manager
    spec:
      containers:
        - name: ldap-user-manager
          image: wheelybird/ldap-user-manager
          ports:
            - containerPort: 80
          env:
            - name: NO_HTTPS
              value: "true"
            - name: LDAP_URI
              value: ldap://openldap
            - name: LDAP_REQUIRE_STARTTLS
              value: "false"
            - name: LDAP_BASE_DN
              value: "dc=kwkaiser,dc=io"
            - name: LDAP_ADMIN_BIND_DN
              value: "cn=admin,dc=kwkaiser,dc=io"
            - name: LDAP_ADMINS_GROUP
              value: admins
            - name: LDAP_ADMIN_BIND_PWD
              value: password
            - name: LDAP_IGNORE_CERT_ERRORS
              value: "true"
            - name: LDAP_VERBOSE_CONNECTION_LOGS
              value: "true"
            - name: LDAP_DEBUG
              value: "true"
      initContainers:
        {{ include "waitFor" (dict "Name" "openldap" "Port" 389) }}