apiVersion: v1
kind: Service
metadata:
  name: ldap-user-manager
spec: 
  selector:
    app: ldap-user-manager
    app.kubernetes.io/name: ldap-user-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 