apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configs
data:
{{- range $path, $bytes := .Files.Glob "config/nginx**" }}
  {{ $cleanedPath := regexReplaceAll "\\/" (trimPrefix "config/nginx/" $path ) "_" }}
  {{ $cleanedPath }}: {{ tpl ($.Files.Get $path) $ | quote }}
{{- end }}