apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/name: nginx
    spec: 
      volumes: 
        {{- range $name := list "nginx-certificate-key" "nginx-certificate" }}
        - name: {{$name}}
          secret:
            secretName: {{ regexReplaceAll "-" $name "." }}
            items:
              - key: value
                path: value
        {{- end }}

        - name: nginx-configs
          configMap:
            name: nginx-configs
            items: 
            {{- range $path, $content := .Files.Glob "config/nginx**" }}
            {{- $cleanedPath := regexReplaceAll "\\/" (trimPrefix "config/nginx/" $path ) "_" }}
              - key: {{ $cleanedPath }}
                path: {{ $cleanedPath }} 
            {{- end }}

      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
            - containerPort: 443

          volumeMounts:
            - name: nginx-certificate
              mountPath: /etc/nginx/keys/{{ .Values.domainName }}.crt
              subPath: value
              readOnly: true
            - name: nginx-certificate-key
              mountPath: /etc/nginx/keys/{{ .Values.domainName }}.key
              subPath: value
              readOnly: true
            
          {{- range $path, $content := .Files.Glob "config/nginx**" }}
          {{- $cleanedPath := regexReplaceAll "\\/" (trimPrefix "config/nginx/" $path ) "_" }}
            - name: nginx-configs
              mountPath: {{ printf "%s%s" "/etc/nginx/" (regexReplaceAll "_"  $cleanedPath "/") }} 
              subPath: {{ $cleanedPath }}
              readOnly: true
          {{- end }} 
      initContainers:
      {{- range $name := list "authelia" "ldap-user-manager" }}
        {{- $p := dict "Name" $name }}
        {{ include "waitFor" $p}}
      {{- end }}