apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: linuxserver/nginx
          ports:
            - containerPort: 80
          volumeMounts:
          {{- range $path, $content := .Files.Glob "config/nginx**" }}
          {{- $cleanedPath := regexReplaceAll "\\/" (trimPrefix "config/nginx/" $path ) "_" }}
            - name: nginx-configs
              mountPath: {{ printf "%s%s" "/config/nginx/" (regexReplaceAll "_"  $cleanedPath "/") }} 
              subPath: {{ $cleanedPath }}
              readOnly: true
          {{- end }} 
      volumes:
        - name: nginx-configs
          configMap:
            name: nginx-configs
            items: 
            {{- range $path, $content := .Files.Glob "config/nginx**" }}
            {{- $cleanedPath := regexReplaceAll "\\/" (trimPrefix "config/nginx/" $path ) "_" }}
              - key: {{ $cleanedPath }}
                path: {{ $cleanedPath }} 
            {{- end }}