apiVersion: v1
kind: Service
metadata:
  name: nginx
spec: 
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: https
      protocol: TCP
      port: 443 
      targetPort: 443
      nodePort: 30443

    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080