apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  replicas: 1
  template:
    metadata:
      labels:
        app: prowlarr
        app.kubernetes.io/name: prowlarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: prowlarr
          image: {{ .Values.image_prowlarr }}
          ports:
            - containerPort: 9696

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: application/prowlarr