apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-user-manager
spec: 
  selector:
    matchLabels:
      app: ldap-user-manager
  replicas: 1 
  template:
    metadata:
      labels: 
        app: ldap-user-manager
        app.kubernetes.io/name: ldap-user-manager
    spec:
      containers:
        - name: ldap-user-manager
          image: wheelybird/ldap-user-manager
          ports:
            - containerPort: 80

          env:
            - name: NO_HTTPS
              value: "true"
            - name: LDAP_URI
              value: ldap://ldap