apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "miniflux.db.password"
  name: minifluxdb
spec:
  selector:
    matchLabels:
      app: minifluxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: minifluxdb
        app.kubernetes.io/name: minifluxdb
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: minifluxdb-db
          image: {{ .Values.image_miniflux_db }}
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniflux.db.password
                  key: value

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 10

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: application/miniflux/db 

