apiVersion: v1
kind: Service
metadata:
  name: minifluxdb
spec:
  selector:
    app: minifluxdb
    app.kubernetes.io/name: minifluxdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

