apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec: 
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels: 
        app: postgres
        app.kubernetes.io/name: postgres
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: application/postgres