apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "n8n.oidc.client.secret"
  name: n8n
spec:
  selector:
    matchLabels:
      app: n8n
  replicas: 1
  template:
    metadata:
      labels:
        app: n8n
        app.kubernetes.io/name: n8n
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: n8n
          image: {{ .Values.image_n8n }}
          ports:
            - containerPort: 5678

          env:
            - name: N8N_HOST
              value: "0.0.0.0"

            - name: N8N_PORT
              value: "5678"

            - name: N8N_PROTOCOL
              value: "https"

            - name: WEBHOOK_URL
              value: "https://workflows.{{ .Values.domainName }}.{{ .Values.tld }}"

            - name: N8N_EDITOR_BASE_URL
              value: "https://workflows.{{ .Values.domainName }}.{{ .Values.tld }}"

            - name: GENERIC_TIMEZONE
              value: "America/New_York"

            - name: N8N_LOG_LEVEL
              value: "info"

            - name: N8N_USER_FOLDER
              value: "/home/node/.n8n"

            - name: N8N_SECURE_COOKIE
              value: "true"

            # OIDC Configuration
            - name: N8N_SSO_OIDC_ENABLED
              value: "true"

            - name: N8N_SSO_OIDC_ISSUER
              value: "https://auth.{{ .Values.domainName }}.{{ .Values.tld }}"

            - name: N8N_SSO_OIDC_CLIENT_ID
              value: "n8n"

            - name: N8N_SSO_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: n8n.oidc.client.secret
                  key: value

            - name: N8N_SSO_OIDC_REDIRECT_URL
              value: "https://workflows.{{ .Values.domainName }}.{{ .Values.tld }}/rest/sso/oidc/callback"

            - name: N8N_SSO_OIDC_SCOPE
              value: "openid profile email"

          volumeMounts:
            - name: data
              mountPath: /home/node/.n8n
              subPath: application/n8n/data

          securityContext:
            runAsUser: 0
            runAsGroup: 0

          livenessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
