{{- if eq .Values.global.domainName "kwkaiser" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dns-poll
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: dns-poll
              image: alpine:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e

                  # Install curl and jq
                  apk add --no-cache curl jq

                  DOMAIN="{{ .Values.global.domainName }}.{{ .Values.global.tld }}"
                  
                  # Get current IPv4 address
                  CURRENT_IP=$(curl -4 -s ifconfig.me/ip)
                  echo "Current IPv4 address: $CURRENT_IP"

                  # Get zone ID
                  ZONE_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}" \
                    -H "Authorization: Bearer ${CF_API_TOKEN}" \
                    -H "Content-Type: application/json")
                  
                  ZONE_ID=$(echo "$ZONE_RESPONSE" | jq -r '.result[0].id // empty')
                  
                  if [ -z "$ZONE_ID" ]; then
                    echo "Error: Could not find zone for domain ${DOMAIN}" >&2
                    exit 1
                  fi
                  
                  echo "Zone ID: $ZONE_ID"

                  # Get all A records
                  DNS_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records?type=A" \
                    -H "Authorization: Bearer ${CF_API_TOKEN}" \
                    -H "Content-Type: application/json")

                  # Parse and update records
                  echo "$DNS_RESPONSE" | jq -r '.result[] | "\(.id)|\(.name)|\(.content)"' | while IFS='|' read -r RECORD_ID RECORD_NAME RECORD_IP; do
                    # Skip root domain and www subdomain
                    if [ "$RECORD_NAME" = "$DOMAIN" ] || [ "$RECORD_NAME" = "www.${DOMAIN}" ]; then
                      echo "Skipping $RECORD_NAME (excluded from auto-update)"
                      continue
                    fi

                    if [ "$RECORD_IP" != "$CURRENT_IP" ]; then
                      echo "Would update $RECORD_NAME from $RECORD_IP to $CURRENT_IP"
                      # TODO: Uncomment to enable actual DNS updates
                      # curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records/${RECORD_ID}" \
                      #   -H "Authorization: Bearer ${CF_API_TOKEN}" \
                      #   -H "Content-Type: application/json" \
                      #   -d "{\"type\":\"A\",\"name\":\"${RECORD_NAME}\",\"content\":\"${CURRENT_IP}\"}"
                      echo "[DRY RUN] Would have updated $RECORD_NAME"
                    else
                      echo "$RECORD_NAME is already set to $CURRENT_IP, skipping"
                    fi
                  done

                  # Send notification
                  curl -d "DNS update check completed. Current IP: $CURRENT_IP" ntfy.sh/q1LvGGrzvMGRxlKF || true
              env:
                - name: CF_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare.api.token
                      key: value
                - name: DOMAIN
                  value: "{{ .Values.global.domainName }}.{{ .Values.global.tld }}"
{{- end }}
