apiVersion: batch/v1
kind: CronJob
metadata:
  name: dns-poll
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: dns-poll
              image: curlimages/curl:latest
              command: ["/bin/sh", "-c"]
              args:
                ["curl -d $(curl -4 ifconfig.me/ip) ntfy.sh/q1LvGGrzvMGRxlKF"]
