apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
spec: 
  selector:
    matchLabels:
      app: ldap
  replicas: 1
  template:
    metadata:
      labels: 
        app: ldap
        app.kubernetes.io/name: ldap
    spec:
      containers:
        - name: ldap
          image: linuxserver/ldap-auth
          ports:
            - containerPort: 8888
            - containerPort: 9000