apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "wireguard.key"
  name: vpn
spec:
  selector:
    matchLabels:
      app: vpn
  replicas: 1
  template:
    metadata:
      labels:
        app: vpn
        app.kubernetes.io/name: vpn
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"
          - name: net.ipv6.conf.all.disable_ipv6
            value: "0"

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        - name: cache-data
          persistentVolumeClaim:
            claimName: cache-nfs

        - name: modules
          hostPath:
            path: /lib/modules

        - name: vpn-configs
          configMap:
            name: vpn-configs
            items:
              - key: config.js
                path: config.js

        {{- range $name := list "wireguard-key" }}
        - name: {{$name}}
          secret:
            secretName: {{ regexReplaceAll "-" $name "." }}
            items:
              - key: value
                path: value
        {{- end }}

      containers:
        - name: wireguard
          image: {{ .Values.image_wireguard }}
          ports:
            - containerPort: 51820

          volumeMounts:
            - name: wireguard-key
              mountPath: /config/wg0.conf
              subPath: value 

            - mountPath: /lib/modules
              name: modules
              readOnly: true

          # Hooks to guarantee we connected to target IP & stayed connected.
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30 && until curl --connect-timeout 10 ifconfig.me | grep -i "{{ .Values.qbittorrentIp }}"; do echo "Waiting for ifconfig response"; sleep 10; done;
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_BIND
                - NET_RAW
                - SYS_MODULE

        - name: qbittorrent
          image: {{ .Values.image_qbittorrent }}
          ports:
            - containerPort: 8080
            - containerPort: 6881

          env:
            - name: PUID
              value: "0"

            - name: PGID
              value: "0"

          volumeMounts:
            - name: vpn-configs
              mountPath: /copy-book.sh
              subPath: copy-book.sh
              readOnly: false

            - name: data
              mountPath: /config
              subPath: application/qbittorrent

            - name: data
              mountPath: /shared/torrents
              subPath: shared/torrents 

            - name: data
              mountPath: /shared/upload
              subPath: shared/upload

            - name: cache-data
              mountPath: /cache/torrents
              subPath: shared/torrents

        - name: thelounge
          image: {{ .Values.image_thelounge }}
          ports:
            - containerPort: 9000

          env:
            - name: PUID
              value: "0"

            - name: PGID
              value: "0"

          volumeMounts:
            - name: data
              mountPath: /config/logs
              subPath: application/thelounge/logs

            - name: data
              mountPath: /config/users
              subPath: application/thelounge/users

            - name: data
              mountPath: /config/packages
              subPath: application/thelounge/packages

            - name: vpn-configs
              mountPath: /config/config.js
              subPath: config.js
              readOnly: false