apiVersion: v1
kind: Service
metadata:
  name: vpn
spec:
  selector:
    app: vpn
    app.kubernetes.io/name: vpn
  ports:
    - protocol: TCP
      name: qbittorrent
      port: 8080
      targetPort: 8080

    - protocol: TCP
      name: thelounge
      port: 9000
      targetPort: 9000

    - protocol: TCP
      name: prowlarr
      port: 9696
      targetPort: 9696

    - protocol: TCP
      name: readarr
      port: 8787
      targetPort: 8787

    - protocol: TCP
      name: radarr
      port: 7878
      targetPort: 7878

    - protocol: TCP
      name: sonarr
      port: 8989
      targetPort: 8989