apiVersion: v1
kind: PersistentVolume
metadata:
  name: 
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: bulk-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /bulk-pool/nfs
    server: 192.168.56.69
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: cache-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /cache-pool/nfs
    server: 192.168.56.69