apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "sparkyfitness.db.password,sparkyfitness.app.db.password,sparkyfitness.api.encryption.key,sparkyfitness.better.auth.secret,sparkyfitness.oidc.clientid,sparkyfitness.oidc.clientsecret"
  name: sparkyfitnessserver
spec:
  selector:
    matchLabels:
      app: sparkyfitnessserver
  replicas: 1
  template:
    metadata:
      labels:
        app: sparkyfitnessserver
        app.kubernetes.io/name: sparkyfitnessserver
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: sparkyfitnessserver
          image: {{ .Values.image_sparkyfitness_server }}
          ports:
            - containerPort: 3010

          env:
            - name: SPARKY_FITNESS_DB_HOST
              value: sparkyfitnessdb

            - name: SPARKY_FITNESS_DB_PORT
              value: "5432"

            - name: SPARKY_FITNESS_DB_NAME
              value: sparkyfitness_db

            - name: SPARKY_FITNESS_DB_USER
              value: sparky

            - name: SPARKY_FITNESS_APP_DB_USER
              value: sparky_app

            - name: SPARKY_FITNESS_FRONTEND_URL
              value: https://fit.{{ .Values.global.domainName }}.{{ .Values.global.tld }}

            - name: SPARKY_FITNESS_EXTRA_TRUSTED_ORIGINS
              value: https://authentik.{{ .Values.global.domainName }}.{{ .Values.global.tld }}

            - name: NODE_ENV
              value: production

            - name: TZ
              value: America/Los_Angeles

            - name: SPARKY_FITNESS_LOG_LEVEL
              value: ERROR

            - name: SPARKY_FITNESS_PUBLIC_API_DOCS
              value: "false"

            - name: SPARKY_FITNESS_DISABLE_SIGNUP
              value: "false"

            - name: SPARKY_FITNESS_ADMIN_EMAIL
              value: karl@kwkaiser.io

            - name: DEV_TOOLS_ENABLED
              value: "false"

            - name: SPARKY_FITNESS_OIDC_AUTH_ENABLED
              value: "true"

            - name: SPARKY_FITNESS_OIDC_PROVIDER_SLUG
              value: authentik

            - name: SPARKY_FITNESS_OIDC_PROVIDER_NAME
              value: authentik

            - name: SPARKY_FITNESS_OIDC_ISSUER_URL
              value: https://authentik.{{ .Values.global.domainName }}.{{ .Values.global.tld }}/application/o/sparky/

            - name: SPARKY_FITNESS_OIDC_SCOPE
              value: "openid email profile"

            - name: SPARKY_FITNESS_OIDC_AUTO_REGISTER
              value: "true"

            - name: SPARKY_FITNESS_OIDC_AUTO_REDIRECT
              value: "true"

            - name: SPARKY_FITNESS_OIDC_ADMIN_GROUP
              value: sparky-admin

            - name: SPARKY_FITNESS_DISABLE_EMAIL_LOGIN
              value: "true"

            - name: SPARKY_FITNESS_FORCE_EMAIL_LOGIN
              value: "false"

            - name: SPARKY_FITNESS_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness.oidc.clientid
                  key: value

            - name: SPARKY_FITNESS_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness.oidc.clientsecret
                  key: value

            - name: SPARKY_FITNESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness.db.password
                  key: value

            - name: SPARKY_FITNESS_APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness.app.db.password
                  key: value

            - name: SPARKY_FITNESS_API_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness.api.encryption.key
                  key: value

            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness.better.auth.secret
                  key: value

          volumeMounts:
            - name: data
              mountPath: /app/SparkyFitnessServer/uploads
              subPath: application/sparkyfitness/uploads

            - name: data
              mountPath: /app/SparkyFitnessServer/backup
              subPath: application/sparkyfitness/backup
