apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea
        app.kubernetes.io/name: gitea
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: gitea
          image: bitnami/gitea
          ports:
            - containerPort: 8096

          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "false"

          volumeMounts:
            - name: data
              mountPath: /bitnami/gitea
              subPath: application/gitea
