apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea
        app.kubernetes.io/name: gitea
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        - name: gitea-configs
          configMap:
            name: gitea-configs
            items:
              - key: app.ini
                path: app.ini

      containers:
        - name: giteadb
          image: postgres
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: password

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: application/gitea/db

        - name: gitea
          image: gitea/gitea
          ports:
            - containerPort: 3000
            - containerPort: 2222

          env:
            - name: GITEA__database__DB_TYPE
              value: postgres

            - name: GITEA__database__HOST
              value: 0.0.0.0:5432

            - name: GITEA__database__NAME
              value: postgres

            - name: GITEA__database__USER
              value: postgres

            - name: GITEA__database__PASSWD
              value: password

          volumeMounts:
            - name: data
              mountPath: /data/gitea
              subPath: application/gitea/data

            - name: data
              mountPath: /data/git/repositories
              subPath: application/gitea/repos

            - name: data
              mountPath: /data/git/lfs
              subPath: application/gitea/lfs

            - name: gitea-configs
              mountPath: /data/gitea/conf/app.ini
              subPath: app.ini
              readOnly: false

        - name: gitea-runner
          image: gitea/act_runner:nightly-dind-rootless

          securityContext:
            privileged: true

          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2376

            - name: DOCKER_CERT_PATH
              value: /certs/client

            - name: DOCKER_TLS_VERIFY
              value: "1"

            - name: GITEA_INSTANCE_URL
              value: "http://gitea"

            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              value: "hiA4VTSnGOJoLrbVOp2ZUc6p7zTgnTguoHqstTyf"

          volumeMounts:
            - name: data
              mountPath: /data
              subPath: application/gitea/runner
