apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "miniflux.db.password"
  name: miniflux
spec:
  selector:
    matchLabels:
      app: miniflux
  replicas: 1
  template:
    metadata:
      labels:
        app: miniflux
        app.kubernetes.io/name: miniflux
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: miniflux-db
          image: {{ .Values.image_miniflux_db }}
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniflux.db.password
                  key: value

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 10

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: application/miniflux/db

        - name: miniflux
          image: {{ .Values.image_miniflux }}
          ports:
            - containerPort: 8080

          env:
            - name: METRICS_COLLECTOR
              value: "1"

            - name: RUN_MIGRATIONS
              value: "1"

            - name: CREATE_ADMIN
              value: "1"

            - name: ADMIN_USERNAME
              value: kwkaiser

            - name: ADMIN_PASSWORD
              value: password

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: miniflux.db.connection.string
                  key: value