apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
spec:
  selector:
    matchLabels:
      app: miniflux
  replicas: 1
  template:
    metadata:
      labels:
        app: miniflux
        app.kubernetes.io/name: miniflux
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

      containers:
        - name: minifluxdb
          image: postgres
          ports:
            - containerPort: 5432

          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 15

          env:
            - name: POSTGRES_USER
              value: miniflux

            - name: POSTGRES_PASSWORD
              value: password

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: application/minifluxdb

        - name: miniflux
          image: miniflux/miniflux:latest
          ports:
            - containerPort: 8080

          env:
            - name: RUN_MIGRATIONS
              value: "1"

            - name: CREATE_ADMIN
              value: "1"

            - name: ADMIN_USERNAME
              value: kwkaiser

            - name: ADMIN_PASSWORD
              value: password

            - name: DATABASE_URL
              value: postgres://miniflux:miniflux@0.0.0.0/miniflux?sslmode=disable
