apiVersion: v1
kind: Service
metadata:
  name: miniflux
spec:
  selector:
    app: miniflux
    app.kubernetes.io/name: miniflux
  ports:
    - protocol: TCP
      name: miniflux-client
      port: 80
      targetPort: 8080

    - protocol: TCP
      name: miniflux-db
      port: 5432
      targetPort: 5432
