apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configs

# Loads all the files in the config/nginx under their filename & substitutes / templates
# any values as necessary. 

data:
  {{- range $path, $bytes := .Files.Glob "config/nginx/**" }}
    {{ $cleanedPath := regexReplaceAll "\\/" (trimPrefix "config/nginx/" $path ) "_" }}
    {{ $cleanedPath }}: {{ tpl ($.Files.Get $path) $ | quote }}
  {{- end }}
