apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec: 
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels: 
        app: nginx
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80 
          volumeMounts:
            - name: nginx-configs
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-configs
              mountPath: /etc/nginx/reverse-proxy.conf
              subPath: reverse-proxy.conf
              readOnly: true
      volumes:
        - name: nginx-configs
          configMap: 
            name: nginx-configs
            items: 
              - key: nginx.conf
                path: nginx.conf 
              - key: reverse-proxy.conf
                path: reverse-proxy.conf