apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    # server {
    #   listen 80 default_server;
    #   listen [::]:80 default_server;


    #   server_name _;

    #   location / {
    #     set $upstream_app calibre;
    #     set $upstream_port 8080;
    #     set $upstream_proto http;
    #     proxy_pass http://google.com
    #     proxy_set_header X-Scheme $scheme;
    #   }
    # }
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html; #Change this line
            index  index.html index.htm;
        }
      }
    } 